services:
  app:
    build: .
    container_name: chatbot_app
    ports:
# REMOVED port mapping ${PORT}:${PORT} for Render deployment
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./data:/data
      - ./scripts:/scripts
    depends_on:
      - qdrant
    command: uvicorn app.api:app --host 0.0.0.0 --port ${PORT:-8000}


  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
# REMOVED port mapping ${QDRANT_PORT}:${QDRANT_PORT} for Render deployment
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
