version: '3.8'

services:
  app:
    build: ./app
    container_name: chatbot_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./data:/data
      - ./scripts:/scripts
    depends_on:
      - qdrant
    command: python main.py


  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  #frontend:
    #build: ./frontend
    #container_name: chatbot_frontend
    #ports:
    #  - "3000:3000"
    #volumes:
    #  - ./frontend:/frontend
    #depends_on:
     # - app

volumes:
  qdrant_data: