services:
  - type: web
    name: chatbot-backend
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
      - key: OPENAI_API_KEY
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: LLAMAPARSE_API_KEY
        sync: false
