name: Keep Render Warm

on:
  schedule:
    - cron: '*/14 * * * *'  # Every 14 minutes
  workflow_dispatch:        # (Optional) Allow manual runs

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render App
        run: curl -s https://your-app.onrender.com
